### ISSUE TITLE
Default source for Relentless Night seems to be broken

### ISSUE THREAD

**Issue by bdgackle** [WulfMarius/Mod-Installer#11]
The link to Relentless Night seems to be broken.  When you select it and click "install" an HTTP 410 error is returned and the mod does not install.

The correct link appears to be (based on a manual download at the given URL):
https://www.moddb.com/downloads/mirror/138754/102/4c4fd20ffd0ea25bb3e0d28593d9ca3d

If I manually replace the existing link with this in sources.json, the mod downloads correctly (I assume this isn't a good way to do it, but it worked for testing).

It *looks* like you can fix this by simply replacing the existing link with the one above on line 32 of:
./descriptions/shieldheart-mod-installer-description.json (looking at the version of the tip of master).  I don't know if there is more involved with that though -- that was based on a quick look, I didn't fully wrap my head around your utility.

The given URL, version number and change date in that file all appear correct, only the MD5 hash in the file link is wrong.  I'm guessing a minor change was done by shieldheart without rolling the version.

I'd send a pull request, but I don't have a machine handy with any of the right toolchains to actually test it.  Sorry!

**Comment by WulfMarius** [comment]
The links on ModDB keep rotating. Not sure why the hash changed, but I think I remember Shield making some quick change.

He wants to migrate the next version to github, which will provide stable download links, but until then they have to be updated every now and then.

Thanks for noticing and letting me know!
