### ISSUE TITLE
Can't refresh sources

### ISSUE THREAD

**Issue by lasoleil** [WulfMarius/Mod-Installer#13]
![sss](https://user-images.githubusercontent.com/46064130/50371736-57382580-05f3-11e9-85f0-7ca3a0aa07be.jpg)
![ddd](https://user-images.githubusercontent.com/46064130/50371744-66b76e80-05f3-11e9-8fec-518c0f17a034.jpg)
When i download new version of modinstaller, i can't refresh the sources

**Comment by WulfMarius** [comment]
I'm confused.

The screenshot shows that the sources are being updated.
There are also releases that are very new (e.g. AmbientLights from 21/12/2018).
Developer-Console is also not marked as "incompatible", despite having a very old release date (04/11/2018). This only works if the sources have been refreshed after the update to 0.6.0 (or later).

So what exactly do you think is not working?

**Comment by lasoleil** [comment]
i refresh the sources so many times, but most of the mods still remain
outdated except some mods like developer console, ambient lights,...

Vào Th 7, 22 thg 12, 2018 vào lúc 16:29 WulfMarius <
notifications@github.com> đã viết:

**Comment by WulfMarius** [comment]
Well, those mods have not been updated yet.

**Comment by lasoleil** [comment]
It's ok, i don't really mind about that. Thanks.

Vào 18:28 Th 7, 22 thg 12 2018 WulfMarius <notifications@github.com đã viết:
