### ISSUE TITLE
NullPointerException on install or update

### ISSUE THREAD

**Issue by jamiecwilliams** [WulfMarius/Mod-Installer#14]
Version 0.61.0 of Mod-Installer is giving the following log output when I attempt to install or update mods after updating AssetLoader to 3.0.0:
```
ERROR: java.lang.NullPointerException
FINISHED
```
Updating AssetLoader to 3.0.0 was successfull, but I then tried to update the Better-Night-Sky and got the above log message. 
I attempted to update Better-Night-Sky after restarting Mod-Installer, but got the same message.
I tried uninstalling Better-Night-Sky, and that was successful, but when I tried to install it again, I got the same error message.
When I tried to install a mod I'd never used before, Wooden statuettes (which has no dependencies), I received the same NullPointerException.

I am using Steam and TLD is at 1.44, patched with ModLoaderInstaller.

**Comment by WulfMarius** [comment]
Comfirmed, found, and fixed.
Excellent description!

New release should be available any minute now.
Thanks for reporting!
