### ISSUE TITLE
Duplicate mods being displayed in mod installer

### ISSUE THREAD

**Issue by mccab22k** [WulfMarius/Mod-Installer#16]
![image](https://user-images.githubusercontent.com/36287726/50779233-05330900-125d-11e9-98ec-9b467953b427.png)

Map tweaks, cooking tweaks, and faster action redux are also displayed as duplicates. At this point I'm not sure what link I pasted in but it was a collection of mods seemingly from AlexTheRegent
Thanks!

**Comment by WulfMarius** [comment]
I think I understand what happened and will add something to the next version to prevent this.

For now, you can do the following to repair this:

* Close Mod-Installer
* Delete the file mod-installer/repository/sources.json (delete no other files!)
* Restart Mod-Installer

You should be asked to add the default source.  
Click "Yes" and then wait for all the mods to be added again.

Thanks for reporting.

**Comment by mccab22k** [comment]
New issue arose--I'll wait until the time specified but just so you know
![image](https://user-images.githubusercontent.com/36287726/50780514-5abce500-1260-11e9-80d3-cfe403ce2c80.png)
