### ISSUE TITLE
Update pls

### ISSUE THREAD

**Issue by vanja-san** [WulfMarius/Mod-Installer#3]
### _In site:_
![default](https://user-images.githubusercontent.com/7201687/42420555-a1e046b0-82f1-11e8-9595-0347cf7978ca.png)

### _In ModInstaller:_
![2018-07-08-21-00-12](https://user-images.githubusercontent.com/7201687/42420581-f03b7c1c-82f1-11e8-9c07-7d13c1c73252.png)

**Comment by WulfMarius** [comment]
Done
