### ISSUE TITLE
There are a couple of suggestions, please see ...

### ISSUE THREAD

**Issue by vanja-san** [WulfMarius/Mod-Installer#4]
> ##### _Sorry for my english, Google translate helped me._

- Can I add the checkbox - "Auto Close" | Example:
![1](https://user-images.githubusercontent.com/7201687/42420685-a55c89c8-82f3-11e8-8d04-65f31fe040f1.png)

- Is it possible to do something like localization? Example:
In courtyard of 2018, but still not everyone is learning other languages!
![3](https://user-images.githubusercontent.com/7201687/42421023-c8ad73f6-82f8-11e8-96f9-fda46ef5b15a.png)
![4](https://user-images.githubusercontent.com/7201687/42421027-cba11bb2-82f8-11e8-99d9-a13029c83199.png)

- Screenshots or at least links to them do not interfere. To have an idea of mod. Example:
![2](https://user-images.githubusercontent.com/7201687/42420800-be942ca0-82f5-11e8-9b73-21b2035bca54.png)

**Comment by WulfMarius** [comment]
Those are good suggestions.

I don't find a lot of time these days, but I'll keep it in mind.
Thanks!
