### ISSUE TITLE
On Linux: mod-installer.jar does not properly detect that it is in the correct directory when run from icon

### ISSUE THREAD

**Issue by kauffy** [WulfMarius/Mod-Installer#7]
For whatever reason, double-clicking the .jar complains that mod-installer-0.3.0.jar is in the wrong directory, despite being right alongside tld.x86 and tld.x86_64.

I cloned the repo to check out the source and it _appears_ to me to be looking for that file correctly (./tld.x86) although it may be that for whatever reason, paths on Linux are being reported differently OR when it launches, it's not launching with that working path. Your Java is very clearly a lot better than mine.

Related to this, when the dialog pops up to inform the user that it's in the wrong directory, the text doesn't wrap, so it goes to ... just before the correct directory is shown.

I've fixed this UI thing, FWIW, though I am having trouble getting my jar to actually run-- it runs from IntelliJ.

**Comment by WulfMarius** [comment]
It looks like the working directory is not properly set when double clicking the JAR.

I will change this from the working directory to the location of the JAR itself. That should solve this problem.  The non-wrapping text in the alert dialog and the URL problem from #8 will be addressed as well.

Was about to wrap up the next release, so these should become available shortly.  
Thanks for reporting.

**Comment by kauffy** [comment]
Excellent!
When I fixed the alert dialog on my end, I also added in all the possible filenames the user should look for, to cut down on confusion if they don't see "tld.exe".

**Comment by WulfMarius** [comment]
Release with bugfix happened almost 2 weeks ago and the issue was not mentioned again.

**Comment by kauffy** [comment]
Can confirm. New version is working as expected.
