### ISSUE TITLE
On Linux: clicking a hyperlink in a mod description does not open a browser/freezes Mod-Installer

### ISSUE THREAD

**Issue by kauffy** [WulfMarius/Mod-Installer#8]
As the title says, if I click on a mod in the list, and its description contains a URL. Clicking the URL makes the URL appear to be a clicked link (it turns to black, and then is surrounded by a dotted-line box).

No browser window opens, but then Mod-Installer is stuck, as though modal.

**Comment by WulfMarius** [comment]
Release with bugfix happened almost 2 weeks ago and the issue was not mentioned again.
